[package]
name = "sf-recipe-calculator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
json = "0.12.4"
ureq = "2.7.1"
lazy_static = "1.4.0"